### PR TITLE
Fix reading configuration from environment for boolean values

### LINKED ISSUE #565: Logging quiet when backgrounded even when logfile is set
Resque log is always empty after some recent updates. May be related to https://github.com/resque/resque-scheduler/pull/559

I use `resque-scheduler` and `capistrano-resque`. Parts of my configuration:

_resque.rake_:

``` ruby
  task :setup_schedule => :setup do
    ENV['VERBOSE'] = '1'
    ENV['QUIET'] = nil
    ENV['LOGFILE'] = Rails.root.join("log", "resque-scheduler.log").to_s
```

_deploy.rb_

``` ruby
set :resque_verbose, true
set :resque_extra_env, "VERBOSE=1"
```

So I tried to enable `VERBOSE` even in different places and it still doesn't work.

This is how capistrano starts scheduler:

```
$ cap production resque:scheduler:start
00:00 resque:scheduler:start
      01 nohup bundle exec rake RAILS_ENV=production PIDFILE=/…/shared/tmp/pids/scheduler.pid BACKGROUND=yes VERBOSE=1 MUTE=1 resque:scheduler >> /dev/null 2>> /dev/null
```

### PR DESCRIPTION
**Pull request by carsonreinke**
Fixes #565 based on comments in #703.

Copied the truthy values from Rails (well modified them).  This retains the default of false unless proving truth.

### CODE REVIEW

File: lib/resque/scheduler/configuration.rb [hunk 1]
```diff
@@ -8,56 +8,61 @@ def configure
         yield self
       end
 
+      attr_writer :environment
+      def environment
+        @environment ||= ENV
```
Comment (iloveitaly) [inline lib/resque/scheduler/configuration.rb:13]: Why not use `ENV` directly here? So folks can customize the configuration without modifying ENV?

File: CHANGELOG.md [hunk 2]
```diff
@@ -6,6 +6,9 @@
 ### Changed
 - Remove support for Ruby < 2.3
 
+### Fixed
+- Reading configuration from environment for boolean values
```
Comment (iloveitaly) [inline CHANGELOG.md:10]: Could we improve this description? The functionality change here is we aren't testing for existence anymore and have specific boolean-looking strings that we look for, correct?

**Review by iloveitaly — CHANGES_REQUESTED** [review]

File: lib/resque/scheduler/configuration.rb (hunk 1 above)
Comment (carsonreinke) [reply lib/resque/scheduler/configuration.rb:13]: @iloveitaly it just makes it easier to write tests to allow this be provided instead of mocking/stubbing.

File: CHANGELOG.md (hunk 2 above)
Comment (carsonreinke) [reply CHANGELOG.md]: @iloveitaly updated!

**Comment by carsonreinke** [comment]
:tada:
